### ISSUE TITLE
documentation/definition: lein run includes lein deps

### ISSUE THREAD

**Issue by winks** [luminus-framework/luminus#102]
I have a pretty basic luminus project (lein new luminus foo +postgres) that was working perfectly with `lein run` yesterday.
A few minutes ago clojars wasn't reachable and `lein run` failed with this error:

```
Dec 14, 2015 9:09:41 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://clojars.org:443: Network is unreachable
Dec 14, 2015 9:09:41 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://clojars.org:443
```

Sure, with enough knowledge that's not a real problem, but at the moment I encountered it I was wondering if the `deps` step is implicit to leiningen or something I missed in the generated `core.clj` - in any case I think it could make sense to document what's going on exactly when doing `lein run` in a new project, as I find the setup here a bit more complicated than usual, especially regarding the per-project `profiles.clj` (which I didn't know from a previous luminus project).

**Comment by yogthos** [comment]
It looks like it would be an issue for Leiningen itself, there's not much that can be done from the template to improve error reporting. I'd open an issue with lein about providing better a more meaningful error when it can't reach repositories/

**Comment by mcferren** [comment]
I am also experiencing this error when I try to upload my app to Heroku

**Comment by natbrown** [comment]
@mcferren seems like it's because [clojars is down](https://www.reddit.com/r/Clojure/comments/3z1lqn/clojarsorg_down/)

**Comment by winks** [comment]
There's an [open issue](https://github.com/technomancy/leiningen/issues/2054) as of yesterday :)

**Comment by natbrown** [comment]
@winks thanks, hadn't seen that!

**Comment by yogthos** [comment]
since this is an internal lein issue, I'm going to close this one
