### ISSUE TITLE
Issue with queries.sql

### ISSUE THREAD

**Issue by winks** [luminus-framework/luminus#103]
Quoting from `database.md`:

````
Conventionally the queries are placed in the 
resources/sql/queries.sql file. However, once your 
application grows you may consider splitting the 
queries into multiple files.
```

Quoting from the `yesql` [README](https://github.com/krisajenkins/yesql):

```
One File, One Query
Create an SQL query. 
Note we can supply named parameters (in snake_case) and a comment string:
```

I had ~15 queries (INSERT, UPDATE, DELETE) in `queries.sql`.
And I just ran into the problem that I couldn't get an `INSERT` query to work because yesql would do a batch query, which of course failed.

Just splitting all the queries to one file per query fixed this.

Not sure if this is a hard yesql requirement, but they seem to encourage it and it also fixed my problem.

**Comment by yogthos** [comment]
I you read further down in the README, Yesql supports [multiple queries per file](https://github.com/krisajenkins/yesql#one-file-many-queries)

>As an alternative to the above, you can have many SQL statements in a single SQL file. The file format is: (<name tag> [docstring comments] <the query>)*

When you place multiple queries in the file then you have to provide the name for each query.

Luminus uses the [conamn](https://github.com/luminus-framework/conman) library to define Yesql queries, and the library supports using multiple files each containing multiple queries, the usage is described in the docs [here](http://www.luminusweb.net/docs/database.md#working_with_yesql).

**Comment by winks** [comment]
Doh, I've quadruple-checked it now.

This (plus light gray text for comments in my IDE) was the culprit:

```
-- name: create-application!
-- create a new application
INSERT INTO applications
(id, name, email, is_active, status, created, updated)
VALUES (:id, :name, :email, 't', 'NEW', NOW(), NOW())

-- name update-application!
-- update an application by id
UPDATE applications
SET name = :name, email = :email, is_active = :is_active,
status = :status, updated = NOW()
WHERE id = :id::uuid
```

Sorry for the noise.

PS: I hate annotations in comments that are not checked by the linter properly...
