### ISSUE TITLE
Server crashes with `async/as-channel`

### ISSUE THREAD

**Issue by damonmcminn** [luminus-framework/luminus#110]
Following the websocket tutorial, I found that the server crashes on calling [ws-handler](https://github.com/luminus-framework/multi-client-ws-immutant/blob/master/src/multi_client_ws/routes/websockets.clj#L28) due to [wrap-formats](https://github.com/luminus-framework/luminus-template/blob/master/src/leiningen/new/luminus/core/src/middleware.clj#L76) middleware trying to JSON encode `object of class: class org.projectodd.wunderboss.web.undertow.async.websocket.UndertowWebsocketChannel`.

Cloning and running https://github.com/luminus-framework/multi-client-ws-immutant worked without issue and upon closer inspection, I see that there is a mismatch between the example repo and source files generated by `lein new luminus ...`.

Removing `wrap-formats` solves the problem. Is this middleware necessary, or is JSON encoded/decoded implicitly without it?

**Comment by yogthos** [comment]
The `wrap-formats` middleware is only necessary for encoding/decoding Ajax requests. It's not compatible with websockets, so those routes shouldn't be wrapped with it. I'll add some docs about that. I also recommend looking at [Sente](https://github.com/ptaoussanis/sente) for anything non-trivial, I found it very handy for working with ws.

**Comment by damonmcminn** [comment]
Ah thanks, sente looks brilliant :)

**Comment by yogthos** [comment]
it's pretty nice :)
