### ISSUE TITLE
Explain webjar

### ISSUE THREAD

**Issue by royalaid** [luminus-framework/luminus#119]
It took quite a bit of searching to figure out where bootstrap was being served from. Because Bootstraps location is completely transparent to the end user finding out how to add CSS libraries of their own might be difficult and it would help to have a brief explanation on how to use and change webjars

**Comment by yogthos** [comment]
That's a good point, I'll look at adding this in the docs.

**Comment by yogthos** [comment]
I've added a [static assets](https://github.com/luminus-framework/luminus/blob/master/resources/md/assets.md) secton, let me know if this looks good to you.

**Comment by royalaid** [comment]
Awesome! I am sure that it will help a lot of people once it gets picked up by google

**Comment by yogthos** [comment]
excellent :)
