### ISSUE TITLE
How would one split queries into multiple files?

### ISSUE THREAD

**Issue by Vaguery** [luminus-framework/luminus#122]
The docs say

> Conventionally the queries are placed in the `resources/sql/queries.sql` file. However, once your application grows you may consider splitting the queries into multiple files.

Assuming I want to split them out (because I do in fact have quite a few), what do I need to do to be able to refer to them, and get them parsed and compiled? Just moving some of them to a new file clearly doesn't work.

**Comment by yogthos** [comment]
You would just pass additional file names to `bind-connection` in the `app.db.core` namespace:

```clojure
(conman/bind-connection conn "sql/queries1.sql" "sql/queries2.sql" "sql/queries3.sql")
```

**Comment by Vaguery** [comment]
That would be good for the docs. Thanks!

**Comment by yogthos** [comment]
Good point, just updated the docs.

**Comment by Vaguery** [comment]
I promise I'll start using pull requests as soon as I'm a bit more comfortable with this all. :)

**Comment by yogthos** [comment]
sounds like a plan :)
