### ISSUE TITLE
REPL development instructions are incorrect or out of date

### ISSUE THREAD

**Issue by scottjacobsen** [luminus-framework/luminus#131]
As a noob I can't figure out how to start the web app from the repl. Following instructions from here: http://www.luminusweb.net/docs/repl.md

```clojure
scott@endor ~/dev/todo% lein repl
user=> (ns todo.core) ;;; Documentation says I should be automatically in this ns, but I'm in user
nil
todo.core=> (http/start {:port 3000 :init init :handler app}) ;;; Docs say this starts the server

CompilerException java.lang.RuntimeException: Unable to resolve symbol: init in this context, compiling:(/private/var/folders/02/_f132dj94_zcrhvhf4t1_wv80000gn/T/form-init2113808848391849401.clj:1:1)
todo.core=> ;;;???
```

**Comment by yogthos** [comment]
Ah that's a bit outdated. I'll have to update the docs for that. The current way is to just run `(start)` in the REPL. The latest version of Luminus uses a `user` namespace found in `env/dev/clj/user.clj`, and the REPL defaults to it. The namespace has helper functions for starting/stoppng/restarting the components.

**Comment by yogthos** [comment]
Let me know if the updated docs make sense.

**Comment by scottjacobsen** [comment]
+1 Thanks. Looks good.
