### ISSUE TITLE
Markdown parser appears to be broken in Chrome

### ISSUE THREAD

**Issue by dviramontes** [luminus-framework/luminus#141]
**Chrome:**
<img width="873" alt="screen shot 2016-06-26 at 12 14 27 pm" src="https://cloud.githubusercontent.com/assets/144226/16363954/cb969fb6-3b97-11e6-8711-a29dd189732d.png">

**Firefox:**
<img width="832" alt="screen shot 2016-06-26 at 12 14 55 pm" src="https://cloud.githubusercontent.com/assets/144226/16363955/cdfad074-3b97-11e6-8cc9-671bb2273b09.png">

Not really sure what is going on but ive been seeing this for a few weeks. 
Doesn't seem to be a problem in Firefox though. Anyways thought I would bring it up to your attention :)

**Comment by lacarmen** [comment]
Which version of Chrome are you using?

**Comment by dviramontes** [comment]
Hi, my apologies:
`Version 51.0.2704.103 (64-bit)`

**Comment by yogthos** [comment]
I would check the plugins that you have in Chrome. I've seen similar reports before due to the fact that the links end in `.md`, and some extension interpret that as Markdown for example.

**Comment by dviramontes** [comment]
Will do thanks!
Closing.
