### ISSUE TITLE
Obsolete information in database.md

### ISSUE THREAD

**Issue by pflingstring** [luminus-framework/luminus#149]
In the last paragraph of **Setting up the database connection** there is old information about initializing and tearing down all components of the app.

> ```The <app>.handler/init and <app>.handler/destroy functions will initialize and tear down any components defined using defstate by calling (mount/start) and (mount/stop) respectively.```

In the current luminus template the `init` and `destroy` functions are removed.

It seems the `start` and `stop` function in `env/dev/clj/user.clj` are used for that purpose now.

**Comment by yogthos** [comment]
thanks, that's definitely dated ;)

**Comment by yogthos** [comment]
the functions that call mount during the normal workflow are actually the `start-app` and `stop-app` in `<app>.core, and the `user` namespace functions are just helpers used to reload state at dev time using the REPL.
