### ISSUE TITLE
Why was Korma removed?

### ISSUE THREAD

**Issue by eprozium** [luminus-framework/luminus#151]
Why was Korma removed? Was it missing some important feature?

**Comment by yogthos** [comment]
Korma relies on an outdated version of clojure.java.jdbc. The API it relies on is incompatible with conman.

**Comment by eprozium** [comment]
> Korma relies on an outdated version of clojure.java.jdbc. 

You mean this ? : https://github.com/korma/Korma/commit/b3a2f6ac45e6cd5ac85047ad5c90e30860204ffa   


> The API it relies on is incompatible with conman.

But that's under your control, isn't it :) ?   https://github.com/luminus-framework/conman

**Comment by yogthos** [comment]
Conman depends on the latest version of clojure.java.jdbc, so that part isn't under my control. I'd basically have to maintain two versions of the library targeting different versions of clojure.java.jdbc. This goes for any other libraries using clojure.java.jdbc, such as Migratus.

Once Korma release happens that's compatible I would consider adding it back as an option. Although, personally I found [HoneySQL](https://github.com/jkk/honeysql) to be a better option as it doesn't rely on macros.

**Comment by eprozium** [comment]
>  I'd basically have to maintain two versions of the library targeting different versions of clojure.java.jdbc. This goes for any other libraries using clojure.java.jdbc

I'm wondering why "central" libraries like "clojure.java.jdbc" aren't backward compatible (JDBC surely is).

> Once Korma release happens that's compatible I would consider adding it back as an option. 

Thank you. 

> Although, personally I found HoneySQL to be a better option as it doesn't rely on macros.

The lifespan of Clojure libraries seems to be even shorter than that of JS libs :).

**Comment by yogthos** [comment]
>I'm wondering why "central" libraries like "clojure.java.jdbc" aren't backward compatible (JDBC surely is).

clojure.java.jdbc has had stable API for years, but the author decided to do a clean up in the latest version and that ended up being a breaking change. It was a major version change and the old API was kept as a deprecation for a couple of releases. The intent was to allow libraries to catch up with it. So, it's not like this happened out of the blue or anything.

I don't know that I agree with that assessment. Korma is a fairly old library, and it hasn't been actively maintained for a while now. So, it's really more of a problem with Korma than anything else here.

**Comment by eprozium** [comment]
> It was a major version change and the old API was kept as a deprecation for a couple of releases. The intent was to allow libraries to catch up with it. 

Most books, blog posts and tutorials haven't caught up, have they :) ?

> Korma is a fairly old library, and it hasn't been actively maintained for a while now.

I only see very many libraries used/referenced everywhere from the same author, in the same state of not "100% ready/mature" but also "not maintained anymore" :( .

**Comment by yogthos** [comment]
>I only see very many libraries used/referenced everywhere from the same author, in the same state of not "100% ready/mature" but also "not maintained anymore" :( .

My recommendation is always to always look at how actively a library is maintained before using it. Part of the goal for Luminus is to provide an up to date template coupled with documentation. This way you don't have to spend the time to find the libraries that work well yourself.

This is the reason Korma is no longer part of Luminus. The project has not been kept up to date and I can't really recommend using it at this point.

**Comment by eprozium** [comment]
> My recommendation is always to always look at how actively a library is maintained before using it. 

That makes sense.  Coming from the Java world however, there exist many very mature libraries that are not actively maintained but are used in a many projects.

> the goal for Luminus is to provide an up to date template coupled with documentation.This way you don't have to spend the time to find the libraries that work well yourself.

Very good and convincing explanation. This statement could belong on the main page: http://www.luminusweb.net/  :)

**Comment by yogthos** [comment]
The library situation in Clojure is definitely more volatile than in Java at this point. People are still figuring out best ways to do things and that means you're going to see some false starts now and then.

Korma was an attempt to create an ORM style abstraction for the database, but people found that it was easier to work with databases directly in Clojure. So, most people are using HoneySQL and HugSQL nowadays, and as a result Korma isn't getting a lot of attention.

I'll take a look at updating the site to mention something along those lines. :)
