### ISSUE TITLE
Luminus' cprop documentation doesn't reflect cprop's own docs

### ISSUE THREAD

**Issue by wgfm** [luminus-framework/luminus#156]
There is a mismatch between Luminus' description of cprop and cprop's own.

According to cprop's documentation, system properties are translated as follows:

```
# system property, cprop style
-Dhttp_pool_socket.timeout=4242
```

becomes

```
; edn representation
{:http {:pool {:socket-timeout 4242}}}
```

That is, underscores mark nesting, and periods are translated to dashes. The Luminus docs claim that dashes are retained and periods signify nesting:

```
#system property, cprop according to Luminus
-Dhttp.pool.socket-timeout=4242
```

Although Luminus' version feels more natural, it is incorrect.

**Comment by yogthos** [comment]
Ah yes, you're absolutely right, and thanks for letting me know. I updated the docs [here](https://github.com/luminus-framework/luminus/blob/master/resources/md/environment.md#managing-environment-variables).

**Comment by wgfm** [comment]
No problem at all! (`-Dnrepl-port` should still be rewritten to use a period)
