### ISSUE TITLE
PDF and cljs-ajax

### ISSUE THREAD

**Issue by monstasat** [luminus-framework/luminus#171]
Hi, I have a question corresponding to issue #167. My purpose is to request PDF from the server, that was generated by clj-pdf, and to show it in the new browser tab. As discussed in #167, swagger-ui shows the response as a stream of symbols, not as a pdf file, and this seems to be ok. But when I request same pdf with cljs-ajax from my luminus-based web-app, the result is the same. 

How can I force my pdf to be shown as a pdf document in a new browser tab when it is received from the server? 
Can this be achieved by supplying :response-format key to the cljs-ajax request?

Thanks in advance!

**Comment by yogthos** [comment]
I replied on the [google group thread](https://groups.google.com/forum/#!topic/luminusweb/gst51A0us3Q). I ended up not using cljs-ajax for that. Instead, you can just make a regular `[:a {:href "/path/to/doc"} "file name"]` and the browser will handle the rest for you.

**Comment by monstasat** [comment]
This is a good solution, but the problem is that I have quite complicated POST request, which has many parameters. These parameters are needed to generate pdf in the necessary way. What can you advice in this case?

**Comment by yogthos** [comment]
You could try doing something like [this](http://stackoverflow.com/questions/2805330/opening-pdf-string-in-new-window-with-javascript) where you return the pdf as a b64 encoded string.

**Comment by monstasat** [comment]
And what to do if my pdf is too large to act like an href after b64 encoding?

**Comment by yogthos** [comment]
Another option you could explore is to use a redirect. You could do a post with the complex parameters, and then generate a link with the resulting PDF. The cljs-ajax handler function could then open the link.

**Comment by monstasat** [comment]
This seems to be an appropriate solution. Thanks a lot!

**Comment by yogthos** [comment]
👍
