### ISSUE TITLE
+service profile conflicts with +auth

### ISSUE THREAD

**Issue by robert-johansson** [luminus-framework/luminus#174]
it works with +auth-jwe though

**Comment by yogthos** [comment]
The reason is that `+auth` profile relies on the `*identity*` var in the `layout` namespace that's not generated when the `+service` profile is used. One option could be to move *identity* to the `middleware` namespace instead.

**Comment by yogthos** [comment]
Yeah, I looked through the template and there's no reason to have the `*identity*` key as the identity is already available in the session. I've removed it and pushed a new version of the template where `+auth` and `+service` are no longer conflicting.

**Comment by robert-johansson** [comment]
OK thanks!
