### ISSUE TITLE
Hoplon template

### ISSUE THREAD

**Issue by Engelberg** [luminus-framework/luminus#175]
Like you, I was under the impression that Hoplon required full buy-in of the boot/hoplon ecosystem.  I was heavily influenced by your article: https://yogthos.net/posts/2016-06-06-WorkingWithHoplon.html and decided to give it a try on a project where reagent wasn't working well for me due to subtle timing issues of when things were mounted in the DOM and when changes were propagated.

I am now completely sold on Hoplon/javelin as a superior tool that completely subsumes my use of reagent and gives me even greater surgical precision to specify reactive behaviors with an even simpler mental model.

It's not too hard to, as you suggest, simply rip out reagent references and put in hoplon/javelin references in a luminus template, but I would certainly value a +hoplon option to the template that does that for me.  I'm planning to recommend this luminus/hoplon approach to others and it would be great to have something that supports it directly.

**Comment by yogthos** [comment]
Yeah, I think having a `+hoplon` profile would be useful. If you'd be up for making a pr I can help with that, otherwise I can take a look when I get a chance. It should be relatively easy to add it based on the existing `+reagent` profile.

**Comment by Engelberg** [comment]
I'm completely ignorant about how templates and profiles are built, but if
I can figure it out quickly, I'd be happy to help.

**Comment by yogthos** [comment]
If you have a minimal sample project configured with Hoplon, I can easily make a profile based on that as well.

**Comment by yogthos** [comment]
I looked at this a bit more, and the only part I'm stuck on is how to set the HTML explicitly in the element [here](https://github.com/luminus-framework/luminus-template/blob/41f90139eb7cc038d5643effcdf6278304a3b956/resources/leiningen/new/luminus/hoplon/src/cljs/core.cljs#L52). I see that it's possible to do in [this](https://github.com/hoplon/hoplon/issues/17) issue, but I wasn't able to get the docs to display. If you could take a look at that, I think the rest is working as expected, and I could push the new template out.

Also, if I did anything that's not idiomatic in Hoplon, feel free to fix that. :)

**Comment by yogthos** [comment]
and got it all figured out, just pushed out a new version with the `+hoplon` profile

implemented by https://github.com/luminus-framework/luminus-template/pull/275
