### ISSUE TITLE
Could not load template, http-kit-features does not exist

### ISSUE THREAD

**Issue by sova** [luminus-framework/luminus#176]
"Could not load template, failed with: java.lang.IllegalAccessError: http-kit-features does not exist"

When  I try to `lein new luminus _appname_ +h2`  or `lein new luminus _appname_ +cljs`

**Comment by yogthos** [comment]
I'm not seeing this issue locally. A couple of things to check would be if you have a specific version of the template in your `~/.lein/profiles.clj` and delete a version that might be cached in `~/.m2/repository/luminus`. You can see the version of the template the app was generated with in the `README.md` in the project. It should say `generated using Luminus version "2.9.11.22"` if it was generated with the current version.

**Comment by sova** [comment]
Ah, it was a templating line in ~/.lein/profiles.clj  Thanks a lot.  Probably would have never found that.

**Comment by yogthos** [comment]
Good to hear
