### ISSUE TITLE
ClassNotFoundException com.fasterxml.jackson.annotation.JsonPropertyDescription  java.net.URLClassLoader.findClass (URLClassLoader.java:381)

### ISSUE THREAD

**Issue by sova** [luminus-framework/luminus#178]
I'm trying to add Datomic to my project and something strange happens when I try and require datomic.api

```
user=> (require '[datomic.api :as d])

ClassNotFoundException com.fasterxml.jackson.annotation.JsonPropertyDescription  java.net.URLClassLoader.findClass (URLClassLoader.java:381)
user=>
```

It seems as though JsonPropertyDescription is a method that is missing from some included jar, but I'm not entirely sure why I need this, nor how to circumvent it.  Thank you, it's kinda driving me crazy at the moment 😅

**Comment by yogthos** [comment]
That one I'm not sure about unfortunately, as I don't use datomic myself. You're definitely right that some implementation jar is missing though. One way to troubleshoot would be to run `lein :tree` to see what's included.

**Comment by eoliphan** [comment]
Hi, I'm using datomic with no problems at this point @sova.  Can you post your project.clj?

**Comment by sova** [comment]
Thanks!  I'm no longer experiencing the issue.
