### ISSUE TITLE
Update repl.md to mention explicitly starting the web-server

### ISSUE THREAD

**Issue by minikomi** [luminus-framework/luminus#180]
It seems that [starting the web server](https://github.com/luminus-framework/luminus-template/commit/df2266b7d8b272c6d23405e57e59ed52f292591a) was removed from the `user/start` function. Calling out to mount `core.http-server` explicitly should be mentioned on the `repl.md` page.

**Comment by yogthos** [comment]
Thanks, updated the docs to mention that.
