### ISSUE TITLE
start excludes http server

### ISSUE THREAD

**Issue by Engelberg** [luminus-framework/luminus#189]
According to the docs:

```
To start the HTTP server and any other components such as databases, run the start function:
(start)
```

According to the code:

```
(defn start []
  (mount/start-without #'app.core/http-server
                       #'app.core/repl-server))
```

Why does the start function explicitly exclude the call to http-server?  What is the rationale, and why does the doc say differently?

**Comment by yogthos** [comment]
The original rationale was that you usually don't need to restart the HTTP server during development. However, I don't really see any harm in doing that either. I'll update the template to remove the HTTP server exclusion.

**Comment by yogthos** [comment]
New version is up on Clojars with the fix.
