### ISSUE TITLE
Bouncer part no longer applicable

### ISSUE THREAD

**Issue by achesnais** [luminus-framework/luminus#190]
Hi :)

On http://www.luminusweb.net/docs/guestbook.md, the tutorial includes bits using the Bouncer library which doesn't appear to be bundled in the latest versions of the Luminus template.

Checking the changelogs it appears Luminus moved to `funcool/struct` – I'm happy to take a shot at updating updating the guestbook tutorial to use struct and submitting a pull request – should I do that or do you just want to take out the validation part altogether?

**Comment by yogthos** [comment]
ah good catch, and thanks a pr would be very much appreciated. :)

**Comment by yogthos** [comment]
I think keeping the validation would be best as it makes the tutorial more comprehensive.

**Comment by yogthos** [comment]
OK I got around to updating the example, it's a [pretty small change](https://github.com/luminus-framework/luminus/commit/2fa4c86427808f8ca3c66e3f66b55a0b159916e9).
