### ISSUE TITLE
not working: lein new luminus my-app; cd my-app; lein run

### ISSUE THREAD

**Issue by MemoWalk** [luminus-framework/luminus#197]
Visiting http://www.luminusweb.net/ following instructions yields this (well known) error:

    ...
    Caused by: java.lang.RuntimeException: Unable to resolve symbol: ok in this context, compiling:(picture_gallery/routes/home.clj:12:19)
    ...

Easy to fix (however I am not acquainted with github so that I could push the change myself):

    XYZ/src/clj/picture_gallery/routes/home.clj

and there

    (defroutes home-routes
        (GET "/" [] (home-page))
        (GET "/docs" [] (response/ok (-> "docs/docs.md" io/resource slurp))))

.

My setup: `Leiningen 2.7.1 on Java 1.8.0_131 OpenJDK 64-Bit Server VM`.

Thanks for the great work!

**Comment by yogthos** [comment]
Thanks for the report, but I'm not able to reproduce this locally. The `README.md` generated with the latest version should have the following at the start:

```
# myapp

generated using Luminus version "2.9.11.81"
```

If you're not seeing that, you're likely on an older version of the template.  It's possible that you have an older version of the template set in your `~/.lein/profiles.clj`.

**Comment by MageMasher** [comment]
@MemoWalk What is your host operating system? I just ran these commands on my mac and it works fine. Also, its a bit further in the future now so I'm not sure if a regression was fixed.

Should this issue still be open?

**Comment by mrayoung** [comment]
Thank you @MemoWalk  
My EVN is Ubuntu it's working after follow your instruction.
