### ISSUE TITLE
"Docsumentation" indexed by Google

### ISSUE THREAD

**Issue by jmmk** [luminus-framework/luminus#199]
On the front page (`http://www.luminusweb.net/`), there is the following markup:

```html
<a href="/docs">
    Doc
    <span class="show-on-mobile">s</span>
    <span class="hide-on-mobile">umentation</span>
</a>
```

It looks like Google indexes this as `Docsumentation`, as seen here:

<img width="645" alt="luminus-docsumentation" src="https://user-images.githubusercontent.com/1122242/31293872-c6e18baa-aaa6-11e7-856a-1c7c7b21127f.png">

**Comment by yogthos** [comment]
heh not sure what can be done there, the reason for the markup is to shrink the title to `Doc` on small screens.

**Comment by jrad87** [comment]
This should work
```
<a href="/docs">
    <span class="show-on-mobile">Docs</span>
    <span class="hide-on-mobile">Documentation</span>
</a>
```

**Comment by yogthos** [comment]
Ah yeah that did the trick, thanks!
