### ISSUE TITLE
website page not rendering correctly

### ISSUE THREAD

**Issue by ikzk** [luminus-framework/luminus#204]
Opening http://www.luminusweb.net/docs/database.html I see it does not render well (tested in firefox 57.0.4 and Chromium 63.0.3239.132)

![2018-01-24-104415_1049x1012_scrot](https://user-images.githubusercontent.com/18649508/35341386-8b638396-00f3-11e8-9f66-b03c7a0b3788.png)

**Comment by yogthos** [comment]
Thanks, there was a typo in the source markdown where a code block wasn't closed causing the odd markup to show up.
