### ISSUE TITLE
missing lein repl out-of-the-box with basic template

### ISSUE THREAD

**Issue by leblowl** [luminus-framework/luminus#206]
Hey @yogthos,

Thanks for the great framework. I am revisiting Clojure and attempting to get a good web dev system set up. I was following the tutorial @ http://www.luminusweb.net/docs/guestbook.html  and started my journey off with `lein new luminus guestbook +h2`. I assumed the command `lein repl` would work out of the box. I had to use `lein new luminus guestbook +h2 +cider` in order to get this functionality. I think there could be a slight improvement to the documentation in order to help beginners with this issue. Any ideas?

**Comment by yogthos** [comment]
The recommended way to use the REPL is by starting the app using `lein run`, and then connecting the editor to the nREPL started by the app. The default port is `7000`. However, you can use `lein repl` as well, once it starts you just have to run the `(start)` function to initialize the app.

**Comment by leblowl** [comment]
@yogthos Thanks, I found this out just now after a little bit more experimentation. Also, re-reading the docs makes this pretty clear to me, although it wasn't totally obvious at first. I wonder if the docs would benefit from an adjustment or if I am the only person who ran into this issue.

**Comment by yogthos** [comment]
I'll add a note about `lein repl` workflow in the guestbook walkthrough, I'm sure you weren't the only one to get tripped up. :)

**Comment by leblowl** [comment]
awesome, thanks
