### ISSUE TITLE
Error in clojurescript.md regarding externs

### ISSUE THREAD

**Issue by feihong** [luminus-framework/luminus#209]
In the [clojurescript doc page](https://github.com/luminus-framework/luminus/blob/master/resources/md/clojurescript.md), it is recommended to put extern code inside `resources/externs.js`, which no longer works. When I try to do that and run `lein uberjar`,  I get the following output:

```
Compiling "target/cljsbuild/public/js/app.js" from ["src/cljc" "src/cljs" "env/prod/cljs"]...
Feb 15, 2018 9:10:15 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: ERROR - Duplicate extern input: /Users/fhsu/work/re-frame-quickstart/resources/externs.js

Feb 15, 2018 9:10:15 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
ERROR: JSC_DUPLICATE_EXTERN_INPUT. Duplicate extern input: /Users/fhsu/work/re-frame-quickstart/resources/externs.js at (unknown source) line (unknown line) : (unknown column)
Successfully compiled "target/cljsbuild/public/js/app.js" in 20.454 seconds.
Created /Users/fhsu/work/re-frame-quickstart/target/uberjar/quickstart-0.1.0-SNAPSHOT.jar
Created /Users/fhsu/work/re-frame-quickstart/target/uberjar/quickstart.jar
```

Renaming `externs.js` to something else eliminates the build error.

Perhaps the docs could be updated by recommending the reader to use the file `resources/my-externs.js` with a warning to not use `resources/externs.js`?

**Comment by yogthos** [comment]
Good idea, just updated the docs to reflect this.
