### ISSUE TITLE
+cider profile removed?

### ISSUE THREAD

**Issue by ailisp** [luminus-framework/luminus#217]
It warns that doesn't has this profile. If so, I'll post a PR to remove that in doc. Thanks!

**Comment by yogthos** [comment]
Thanks, my understanding is that the profile is no longer necessary with the newer versions of cider, hence why it was removed. A PR for the docs would be great.

**Comment by ailisp** [comment]
Thanks for confirming. I just made https://github.com/luminus-framework/luminus/pull/218
