### ISSUE TITLE
Missing words in websockets guide?

### ISSUE THREAD

**Issue by teodorlu** [luminus-framework/luminus#219]
Hello!

In `resources/md/websockets.md`, line 125, this sentence seems to be missing something:

_The macro creates accepts the request as its argument and binds the value of the `:async-channel` key to the second paramets representing the name of the channel._

Perhaps _the macro creates **a handler that** ..._?

Teodor

**Comment by yogthos** [comment]
Thanks, yes it is talking about the handler, I updated the doc file.
