### ISSUE TITLE
Upstart in deployment.md

### ISSUE THREAD

**Issue by teodorlu** [luminus-framework/luminus#221]
Hello!

First, thank you so much for the thoroughly well-made Luminus template and its fine documentation. I've learned so much in the last days.

In docs/deployment.md, Upstart is referred to the current init system of Ubuntu. On Ubuntu 16.04 LTS and 18.04 LTS, systemd is default. The upstart documentation seems to be written about three years ago.

- Should the docs perhaps be updated to reflect that systemd is the default init system of recent Ubuntu distributions?
- Or is it reasonable to drop docs for 3+ years old Ubuntu releases?

Regards,
Teodor

**Comment by yogthos** [comment]
Hi,

I think it's probably reasonable to drop the docs for the old releases at this point. Anybody setting up new servers would presumably at least be using the latest LTS. Would you be up for doing a PR to update the docs? :)

**Comment by teodorlu** [comment]
Gladly :)
