### ISSUE TITLE
Using +shadow-cljs has badly formatted dependency

### ISSUE THREAD

**Issue by gleenn** [luminus-framework/luminus#238]
Looks like something was suppose to be a variable but is processed as a string. In my project.clj file in the dependencies section (verbatim):

[thheller/shadow-cljs shadow-version :scope "provided"]

Pretty sure that "shadow-version" is supposed to be an actual version string because when I run `lein deps` I get:

Could not find artifact thheller:shadow-cljs:jar:shadow-version in central (https://repo1.maven.org/maven2/)
Could not find artifact thheller:shadow-cljs:jar:shadow-version in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.

**Comment by gleenn** [comment]
Looks like in:

src/leiningen/new/shadow_cljs.clj

There is this code:

(def shadow-cljs-dependencies '[[com.google.javascript/closure-compiler-unshaded "v20190618":scope "provided"]
                                 [org.clojure/google-closure-library "0.0-20190213-2033d5d9":scope "provided"]
                                 [thheller/shadow-cljs shadow-version :scope "provided"]])

Should be this:
(def shadow-cljs-dependencies `[[com.google.javascript/closure-compiler-unshaded 
"v20190618":scope "provided"]
                                 [org.clojure/google-closure-library "0.0-20190213-2033d5d9":scope "provided"]
                                 [thheller/shadow-cljs ~shadow-version :scope "provided"]])

**Comment by yogthos** [comment]
Hi,

Thanks for the heads up, just pushed out a fix.
