### ISSUE TITLE
Websockets page does not contain an example for the new default server Jetty

### ISSUE THREAD

**Issue by sorsasampo** [luminus-framework/luminus#245]
The Websockets page contains websocket examples for Immutant and HTTP KIT, but not for the new default server Jetty (since luminus-template 3.37).

http://www.luminusweb.net/docs/websockets.html

**Comment by yogthos** [comment]
The official Jetty adapter doesn't appear to provide Websocket support, I'd recommend using HTTP Kit if you need Websockets. It might make sense to switch Luminus to use it as the default.

**Comment by sorsasampo** [comment]
I think websocket support is kind of important nowadays, so I would personally find it sensible to default to a server that supports them. I'm closing this issue as there is no way to provide an example for an implementation that does not exist!

**Comment by yogthos** [comment]
I agree that ws support is important, and I'll investigate what might be the best option going forward. I'm leaning towards Aleph as the default, but it has a couple of issues that I'd like to see addressed first.
