### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by nkabir** [luminus-framework/luminus#252]
...

Selmer provides two types of tags. The **frist** kind are inline tags such as the extends and include tags. These tags are self contained statements and do not require an end tag. The other type is the block tags. These tags have a start and an end tag, and operate on a block of text. An example of this would be the if ... endif block.

...

https://github.com/luminus-framework/luminus/blob/master/resources/md/html_templating.md#tags

**Comment by yogthos** [comment]
thanks, updated
