### ISSUE TITLE
Improve getting started documentation 

### ISSUE THREAD

**Issue by gbonfant** [luminus-framework/luminus#60]
Hi,

I'm a newcomer to Luminus and Clojure in general. While going through the excellent getting started documentation (specifically [handling form input](http://www.luminusweb.net/docs#creating_pages_and_handling_form_input)) I found myself getting an exception due to a couple of functions not being properly referenced in the namespace.

The first of them was `redirect`:

```bash
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: redirect in this context, compiling:(guestbook/routes/home.clj:28:9)
```

The second was `POST`:

```bash
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: POST in this context, compiling:(guestbook/routes/home.clj:37:3)
```

Both are easily fixed by adding ring and defining POST in the namespace.

```clojure
[compojure.core :refer [defroutes GET POST]]
[ring.util.response :refer [redirect]]
```

I was thinking of opening a PR to improve the documentation on this step but I'm not sure _referencing_ is the correct term or whether you'd like the documentation to change. What do you think?

Thanks!

**Comment by yogthos** [comment]
I think *referencing* is the right way to describe it, the other way would be to say "to use" or "to require", but I've seen all three variations used. I definitely appreciate doc improvements such as these, since it's something that will likely trip others up as well.
