### ISSUE TITLE
Documentation request - clj-ajax

### ISSUE THREAD

**Issue by Engelberg** [luminus-framework/luminus#70]
Currently, the documentation for clj-ajax, both on the luminus site (http://www.luminusweb.net/docs/clojurescript.md#ajax) and on the clj-ajax github site is a bit too sparse.  I'm having difficulty figuring out how to use it without more information about:

* What does the return value of these functions look like?  How do I extract the actual EDN/JSON/TRANSIT/RAW value embedded in the response?

* Can this library be used to fetch data from other websites with a REST API?  If so, what other tricks are necessary to do that?

* What is the behavior of the call if no handler is supplied?

**Comment by yogthos** [comment]
Good ideas, I'll add some docs to that effect. Meanwhile there's more detailed documentation on the library page as well https://github.com/JulianBirch/cljs-ajax

**Comment by yogthos** [comment]
I've updated the docs, but to answer the questions specifically:

The return value will be the deserialized server response, the library tried to automatically figure out the format based on the response headers. On the server side ring-middleware-format library is used to encode/decode the requests and responses. It uses the `Accept` header in the request to decide on the format. So, the requests should contain the header for the format you're using e.g: `:headers {"Accept" "application/transit+json"}`, this is already described in the examples in the docs.

The library can be used to fetch data from other sites, but most browsers will likely block such behavior as it's commonly an indication of a malicious attack.

When no handler is specified then the library will call the service and ignore the response.
