### ISSUE TITLE
adding history to cljs template

### ISSUE THREAD

**Issue by Engelberg** [luminus-framework/luminus#71]
I'm not having any luck adding history to the cljs luminus template.

I added the appropriate requires/imports and added this code to the core.cljs file:

```clojure
(let [h (History.)]
  (goog.events/listen h EventType/NAVIGATE #(secretary/dispatch! (.-token %)))
  (doto h (.setEnabled true)))
```

This doesn't appear to do anything.  Any ideas how to make this work?

Also, ideally, I'd like things to get routed properly when a URL is typed into the browser with the # tag.

Thanks.

**Comment by yogthos** [comment]
you can take a look at how the Reagent template sets it up [here](https://github.com/reagent-project/reagent-template/blob/master/src/leiningen/new/reagent/src/cljs/reagent/core.cljs)  and the secretary [docs](https://github.com/gf3/secretary) have examples as well.

**Comment by Engelberg** [comment]
The thing that threw me off is that this added code only works if you also convert the route dispatches in the links to normal <a href> tags.  It doesn't work as-is with the existing template.  So the template is confusing right now, and the fact that one of the links is an <a href> and the other two are not compounds the confusion.  I'd recommend unifying it, and consider the possibility of including this snippet directly in the template.  It seems more likely that people will want to see a version that enables the browser's back button versus a version that can't do that.

**Comment by yogthos** [comment]
That's a good suggestion, I'll update the template to be closer to the Reagent one.

**Comment by yogthos** [comment]
Just updated the template to setup history by default the way the Reagent template does.
