### ISSUE TITLE
figwheel httpclient conflict with google-http-client-jackson2

### ISSUE THREAD

**Issue by aaronblenkush** [luminus-framework/luminus#75]
I'm not sure whether this is a bug or a misconfiguration in my project. It seems to be some kind of namespace conflict?

If I add the following dependency to `project.clj`:

    [com.google.http-client/google-http-client-jackson2 "1.20.0"]

Then when I run `lein figwheel` I get the following error:

> java.lang.ClassNotFoundException: org.apache.http.conn.scheme.SchemeSocketFactory

Adding the following dependency fixes the issue:

    [org.apache.httpcomponents/httpclient "4.4.1"]

**Comment by yogthos** [comment]
It sounds like the dependency conflicts with one of the figwheel dependencies, and your solutions looks like the right way to address it. This doesn't appear like an issue with Luminus itself though.
