### ISSUE TITLE
Q: Sqlite Support

### ISSUE THREAD

**Issue by pjhampton** [luminus-framework/luminus#85]
Does luminus no longer support command-line invocation of sqlite database support? I ran the following command with no success:

`lein new luminus testapp +sqlite`

I received the following message: 

> Unrecognized options: +sqlite 
> Supported options are: +site, +h2, +dailycred, +jetty, +cljs, +sassc, +swagger, +auth, +war, +http-kit, +cucumber, +aleph, +mongodb, +postgres, +mysql

I thought by running with no options it would default, but no. Am I missing something, or am I just imagining this was originally an option? Sorry for the noob question!

**Comment by yogthos** [comment]
There hasn't been an option for a while. The H2 is used by default for the embedded db, but it wouldn't be difficult to add an option for sqlite back in as well.

**Comment by yogthos** [comment]
just added the `+sqlite` profile in the latest
