### ISSUE TITLE
lein uberjar - app.js not found

### ISSUE THREAD

**Issue by clojurehunter** [luminus-framework/luminus#89]
When compiling Luminus project 
"$ lein new luminus app +cljs +swagger +auth +mongodb"
"$ lein uberjar" - all goes well, then I run the JAR command "$ java -jar target/app.jar"
He also runs without errors.

The problem is that the browser in the debugger I get an error "/js/app.js 404" and "/css/screen.css"
On the server in the folder "/resources/public/js/app.js" and "/resources/public/css/screen.css" this files is present.

My settings should default profiles:
: profiles
  {: uberjar {: omit-source true
             : env {: production true}
              : hooks [leiningen.cljsbuild]
              : cljsbuild
              {: jar true
               : builds
               {: app
                {: source-paths ["env / prod / cljs"]
                 : compiler {: optimizations: advanced: pretty-print false}}}}
             
             : aot: all}
...}

**Comment by yogthos** [comment]
You have to start the ClojureScript compiler in dev mode using

    lein figwheel

**Comment by clojurehunter** [comment]
But "lein figwheel" did not care to come production?
I got to solve the problem: everything was due to the fact that I have not added (routes/resources "/") in my routes!

**Comment by yogthos** [comment]
ClojureScript gets compiled using the [lein-cljsbuild](https://github.com/emezeske/lein-cljsbuild) plugin. The plugin is run by Figwheel during development, and it gets triggered when the uberjar task is run.

**Comment by clojurehunter** [comment]
Now, I completely understand. Thank you for your help

**Comment by yogthos** [comment]
no worries
