### ISSUE TITLE
Accessing ENUM in Postgresql

### ISSUE THREAD

**Issue by Ninerian** [luminus-framework/luminus#91]
I want to write into a colum with type ENUM, but i get the error message: ```ERROR: column \"country_code\" is of type country_codes but expression is of type character varying```

I found a hint at stackoverflow, passing an key :stringtype "unspecified". http://stackoverflow.com/questions/14719207/how-do-you-insert-a-postgres-enum-value-using-clojure-jdbc

But this didn't helped. Do you know how to solve this?

**Comment by yogthos** [comment]
I haven't tried this myself, but sounds like it may be an issue with the [clojure.java.jdbc](https://github.com/clojure/java.jdbc) library. Probably would be best to open the issue there.

**Comment by yogthos** [comment]
I' going to close this one since it's not luminus specific and needs to be fixed in the sql library
