### ISSUE TITLE
documentation: relinking "/docs" to "/md"

### ISSUE THREAD

**Issue by tolitius** [luminus-framework/luminus#93]
was reading about [Managing Component Lifecycle](https://github.com/luminus-framework/luminus/blob/master/resources/md/components.md) :) on [Configuring the Database](https://github.com/luminus-framework/luminus/blob/master/resources/md/database.md) page, and noticed that the link to "Managing Component Lifecycle" is broken, since it links to "/docs" vs. "/md".

since I am not sure how things are meant to be organized (I see that some of the links are to specific commits, and there is also `docs-1` section), creating an issue rather than a pull request.

here are the affected files, as far I can tell:

```clojure
resources/docs-1.x/database.md: ...[migrations section](/docs/migrations.md)
resources/docs-1.x/requests.md: ...[response types](/docs/responses.md)
resources/docs-1.x/security.md: ...[routing section](/docs/routes.md#marking_routes_as_restricted)
resources/md/database.md: ...[Database Migrations](/docs/migrations.md)
resources/md/database.md: ...[Managing Component Lifecycle](/docs/components.md)
resources/md/repl.md: ...[deployment section](/docs/deployment.md#enabling_nrepl)
resources/md/requests.md: ...[response types](/docs/responses.md)
resources/md/routes.md: ...[here](/docs/security.md#cross_site_request_forgery_protection)
resources/md/security.md: ...[Routing section](/docs/routes.md#restricting_access)
resources/md/security.md: ...[routing section](/docs/routes.md#marking_routes_as_restricted)
resources/md/security.md: ...[here](/docs/services.md#csrf)
```

**Comment by yogthos** [comment]
The `/docs` is actually the correct path, what happens though is that the site refreshes itself periodically from github and if you hit it at that time the docs won't be loaded. I'll update to make sure the existing copy is kept while refresh happens.

**Comment by tolitius** [comment]
ah.. makes sense. this is not meant to be read on the github, but rather on the http://www.luminusweb.net/docs/components.md ok, not a problem then.

**Comment by yogthos** [comment]
as a side note, if you find anything off in the description or would like to add anything do feel free to pr :)
