### ISSUE TITLE
ring-logger-timbre should be suggested as useful library instead of ring-logger

### ISSUE THREAD

**Issue by nberger** [luminus-framework/luminus#96]
Given that luminus uses `com.taoensso/timbre` as the logging solution, [ring-logger-timbre](https://github.com/nberger/ring-logger-timbre) is a better suggestion instead of [ring-logger](https://github.com/nberger/ring-logger), because it offers a better integration with timbre.

I can send a PR with this minor change if you want me to do so.

**Comment by yogthos** [comment]
Great suggestion, just updated the docs. :)

**Comment by nberger** [comment]
Cool, thanks :)
