### ISSUE TITLE
Sass template support live compilation

### ISSUE THREAD

**Issue by Naomarik** [luminus-framework/luminus#97]
Would be awesome if the sass template included a watch for sass changes to automatically compile them on save.
https://github.com/vladh/lein-sassy

Just getting my feet wet with the whole clojure/figwheel stack and this is probably the only thing I'd have to figure out how to do before being productive immediately.

**Comment by yogthos** [comment]
that seems like a good idea, I'll take a look at adding this to the template

**Comment by yogthos** [comment]
I added the plugin for the `+sassc` profile, you can try this out locally by cloning the template and doing `lein install`. If everything looks good then I could push this out in next release.

**Comment by yogthos** [comment]
new release is out if the feature's not working as expected then we can reopen this
